/*
  write-config.js
  Build-time helper for Netlify: creates `app-config.js` from environment variables.
  Ensures we don't store anon/service keys in source control.
*/
const fs = require('fs');
const path = require('path');

const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || '';

const content = `/* Generated by write-config.js - do not commit secrets */\nwindow.APP_CONFIG = {\n  supabaseUrl: "${supabaseUrl}",\n  supabaseAnonKey: "${supabaseAnonKey}"\n};\n`;

fs.writeFileSync(path.join(__dirname, 'app-config.js'), content, { encoding: 'utf8' });
console.log('app-config.js written (supabaseUrl set:', !!supabaseUrl, ')');
